/**
 * Generates a robust, unique CSS selector for a DOM element.
 * Priority: id > name > aria-label > data-* > placeholder > submit >
 *           href > title > role > stable class > ancestor-based > structural path.
 */
export function generateSelector(el: Element): string {
  // 1. id attribute
  const id = el.getAttribute('id');
  if (id && !isAutoGeneratedId(id)) {
    const candidate = `#${CSS.escape(id)}`;
    if (isUnique(candidate)) return candidate;
  }

  const tag = el.tagName.toLowerCase();

  // 2. name attribute on form elements
  const name = el.getAttribute('name');
  if (name && isFormElement(el)) {
    const candidate = `${tag}[name="${CSS.escape(name)}"]`;
    if (isUnique(candidate)) return candidate;
  }

  // 3. aria-label
  const ariaLabel = el.getAttribute('aria-label');
  if (ariaLabel) {
    const candidate = `[aria-label="${CSS.escape(ariaLabel)}"]`;
    if (isUnique(candidate)) return candidate;
    const withTag = `${tag}[aria-label="${CSS.escape(ariaLabel)}"]`;
    if (isUnique(withTag)) return withTag;
  }

  // 4. data-testid / data-cy / data-test / data-qa
  for (const attr of ['data-testid', 'data-cy', 'data-test', 'data-qa']) {
    const val = el.getAttribute(attr);
    if (val) {
      const candidate = `[${attr}="${CSS.escape(val)}"]`;
      if (isUnique(candidate)) return candidate;
    }
  }

  // 5. placeholder
  const placeholder = el.getAttribute('placeholder');
  if (placeholder && (tag === 'input' || tag === 'textarea')) {
    const candidate = `${tag}[placeholder="${CSS.escape(placeholder)}"]`;
    if (isUnique(candidate)) return candidate;
  }

  // 6. submit button
  const type = el.getAttribute('type');
  if (type === 'submit') {
    const value = el.getAttribute('value');
    const candidate = value
      ? `${tag}[type="submit"][value="${CSS.escape(value)}"]`
      : `${tag}[type="submit"]`;
    if (isUnique(candidate)) return candidate;
  }
  if (tag === 'button' && type) {
    const candidate = `button[type="${CSS.escape(type)}"]`;
    if (isUnique(candidate)) return candidate;
  }

  // 7. href on links
  if (tag === 'a') {
    const href = el.getAttribute('href');
    if (href && href !== '#' && !href.startsWith('javascript:')) {
      const candidate = `a[href="${CSS.escape(href)}"]`;
      if (isUnique(candidate)) return candidate;
    }
  }

  // 8. title attribute
  const title = el.getAttribute('title');
  if (title) {
    const candidate = `${tag}[title="${CSS.escape(title)}"]`;
    if (isUnique(candidate)) return candidate;
  }

  // 9. role attribute
  const role = el.getAttribute('role');
  if (role) {
    const candidate = `${tag}[role="${CSS.escape(role)}"]`;
    if (isUnique(candidate)) return candidate;
    if (ariaLabel) {
      const withLabel = `[role="${CSS.escape(role)}"][aria-label="${CSS.escape(ariaLabel)}"]`;
      if (isUnique(withLabel)) return withLabel;
    }
  }

  // 10. stable class combination
  const stableClasses = getStableClasses(el);
  if (stableClasses.length > 0) {
    const candidate = `${tag}.${stableClasses.map(CSS.escape).join('.')}`;
    if (isUnique(candidate)) return candidate;
  }

  // 11. Walk up to nearest identifiable ancestor and build a short descendant selector
  const ancestorSel = findAncestorSelector(el);
  if (ancestorSel) return ancestorSel;

  // 12. structural fallback
  return buildStructuralPath(el);
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function isUnique(selector: string): boolean {
  try {
    return document.querySelectorAll(selector).length === 1;
  } catch {
    return false;
  }
}

function isFormElement(el: Element): boolean {
  const tag = el.tagName.toLowerCase();
  return tag === 'input' || tag === 'textarea' || tag === 'select';
}

function isAutoGeneratedId(id: string): boolean {
  if (/^ember\d+$/i.test(id)) return true;
  if (/^react-select-\d/.test(id)) return true;
  if (/^__next/.test(id)) return true;
  if (/^radix-:r/.test(id)) return true;
  if (/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id)) return true;
  if (/\d{4,}/.test(id)) return true;
  return false;
}

function isStableClass(cls: string): boolean {
  if (cls.length < 3) return false;
  if (/\d{3,}/.test(cls)) return false;
  if (/^[a-z][a-z0-9-]+_[a-z0-9]{5,}$/i.test(cls)) return false;
  return true;
}

function getStableClasses(el: Element): string[] {
  return Array.from(el.classList).filter(isStableClass);
}

/** Try to find a unique selector by combining a nearby ancestor's selector with a short child path. */
function findAncestorSelector(el: Element): string | null {
  let current = el.parentElement;
  let depth = 0;
  const childTag = el.tagName.toLowerCase();

  while (current && current !== document.documentElement && depth < 4) {
    const anchorSel = getDirectSelector(current);
    if (anchorSel) {
      // Try: ancestor > childTag
      const simple = `${anchorSel} ${childTag}`;
      if (isUnique(simple)) return simple;
      // Try: ancestor > childTag (direct child)
      const direct = `${anchorSel} > ${childTag}`;
      if (isUnique(direct)) return direct;
    }
    current = current.parentElement;
    depth++;
  }
  return null;
}

/** Returns a simple unique selector for an element, or null if none found quickly. */
function getDirectSelector(el: Element): string | null {
  const id = el.getAttribute('id');
  if (id && !isAutoGeneratedId(id)) {
    const candidate = `#${CSS.escape(id)}`;
    if (isUnique(candidate)) return candidate;
  }
  const tag = el.tagName.toLowerCase();
  if (tag === 'a') {
    const href = el.getAttribute('href');
    if (href && href !== '#' && !href.startsWith('javascript:')) {
      const candidate = `a[href="${CSS.escape(href)}"]`;
      if (isUnique(candidate)) return candidate;
    }
  }
  const ariaLabel = el.getAttribute('aria-label');
  if (ariaLabel) {
    const candidate = `[aria-label="${CSS.escape(ariaLabel)}"]`;
    if (isUnique(candidate)) return candidate;
  }
  for (const attr of ['data-testid', 'data-cy', 'data-test', 'data-qa']) {
    const val = el.getAttribute(attr);
    if (val) {
      const candidate = `[${attr}="${CSS.escape(val)}"]`;
      if (isUnique(candidate)) return candidate;
    }
  }
  const name = el.getAttribute('name');
  if (name && isFormElement(el)) {
    const candidate = `${tag}[name="${CSS.escape(name)}"]`;
    if (isUnique(candidate)) return candidate;
  }
  return null;
}

function buildStructuralPath(el: Element): string {
  const parts: string[] = [];
  let current: Element | null = el;

  while (current && current !== document.documentElement) {
    const parent = current.parentElement;
    if (!parent) break;

    const tag = current.tagName.toLowerCase();
    const siblings = Array.from(parent.children).filter(
      (c) => c.tagName === current!.tagName
    );

    const part =
      siblings.length > 1
        ? `${tag}:nth-child(${getChildIndex(current)})`
        : tag;

    parts.unshift(part);

    const candidate = parts.join(' > ');
    if (isUnique(candidate)) return candidate;

    current = parent;
  }

  return parts.join(' > ');
}

function getChildIndex(el: Element): number {
  let index = 1;
  let sibling = el.previousElementSibling;
  while (sibling) {
    index++;
    sibling = sibling.previousElementSibling;
  }
  return index;
}
